### ISSUE TITLE
Where to find the manufacturer plugins?

### ISSUE THREAD

**Issue by lukecyca** [richardingham/octopus#18]
I got octopus installed, but I can't find where the code for the manufacturer plugins is actually located. From the documentation it looks like there are plugins for 10 manufacturers, but I can only find a repo for WPI.

Specifically I am looking for the Gilson code so I can run a 233XL Sampler, a 402 Syringe pump, and a few other devices.

I did find this unrelated [Gilson402SyringePumpControl](https://github.com/london-biohackers/Gilson402SyringePumpControl) repo which is very useful, but only covers the one device.

Any help or pointers would be appreciated!

cc: @richardingham @olliemay @andyfinity

**Comment by richardingham** [comment]
Hi,

You actually have to go back to an earlier commit to find the Gilson components. I didn't have access to the Gilson kit anymore so couldn't test if the code still worked after various changes, so I didn't want to invest effort in converting them to plug-in style.

https://github.com/richardingham/octopus/blob/include-editor/octopus/manufacturer/gilson.py

If there's anything that doesn't make sense I can try to remember...!

Richard
