### ISSUE TITLE
Dropping crc16 dependency by including a pure python implementation of CRC16

### ISSUE THREAD

**Issue by dcambie** [richardingham/octopus#6]
Hi Richard,

The crc16 dependency (needed for wpi.py) is a bit problematic on Win as the crc16 package requires compilation and no binaries have been released for Python version>3.3[1]

The original repo at [https://github.com/gtrafimenkov/pycrc16] also has a pure python implementation of the CRC16 algo (see 
[here](https://github.com/gtrafimenkov/pycrc16/blob/master/python3x/crc16/crc16pure.py)).

Unfortunately we don't have an Aladdin syringe pump to test that, but would you be open to include this file directly in octopus to remove this problematic dependency?
That module is small, licensed LGPL, and will likely never need to be updated (upstream there have been no commits in the last 10 years anyway...)

[1] See https://code.google.com/archive/p/pycrc16/downloads

**Comment by richardingham** [comment]
Thanks for the suggestion. This has been resolved by commit 2c48a9ec54db73e1aa1d072c09936990679e5846.
